apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: folio-bot-mackerel
spec:
  schedule: "22,52 0-6,9 * * 1-5" # for UTC
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: folio-bot-mackerel
            image: index.docker.io/koukidan/folio-bot
            args: ["python", "folio.py"]
            env:
              - name: USERNAME
                valueFrom:
                  secretKeyRef:
                    name: folio-bot-credentials
                    key: username
              - name: PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: folio-bot-credentials
                    key: password
              - name: MACKEREL_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: folio-bot-credentials
                    key: mackerel-api-key
              - name: MACKEREL_SERVICE_URL
                valueFrom:
                  secretKeyRef:
                    name: folio-bot-credentials
                    key: mackerel-service-url
          restartPolicy: Never

